
name: Azure Terraform Multi Environment Deployment

on:

  push:
    branches:
      - main



permissions:
  contents: read

jobs:

  terraform-validation:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
           terraform_version: "1.14.5"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate


  deploy-dev:

    needs: terraform-validation

    runs-on: ubuntu-latest

    environment:
      name: dev

    defaults:
      run:
        working-directory: terraform/

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup the terraform  
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.5"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan for dev
        run: |
          terraform plan \
          -var-file=dev.tfvars \
          -out=dev.tfplan

      - name: Terraform Apply for dev
        run: |
          terraform apply \
          -auto-approve \
          dev.tfplan



  deploy-test:

    needs: deploy-dev

    runs-on: ubuntu-latest

    environment:
      name: test

    defaults:
      run:
        working-directory: terraform/

    steps:

      - name: checkout code
        uses: actions/checkout@v4


      - name: setup the terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.5"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan for test
        run: |
          terraform plan \
          -var-file=test.tfvars \
          -out=test.tfplan

      - name: Terraform Apply for test
        run: |
          terraform apply \
          -auto-approve \
          test.tfplan



  deploy-prod:

    needs: deploy-test

    runs-on: ubuntu-latest

    environment:
      name: prod

    defaults:
      run:
        working-directory: terraform/

    steps:

      - name: checkout code
        uses: actions/checkout@v4


      - name: setuo terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.5"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan for prod
        run: |
          terraform plan \
          -var-file=prod.tfvars \
          -out=prod.tfplan

      - name: Terraform Apply for prod
        run: |
          terraform apply \
          -auto-approve \
          prod.tfplan